#!/bin/bash

# Get the path of the current directory
CURR_DIR="$(cd "$(dirname "$0")" && pwd)";
# SCRIPT_NAME="$(basename "${BASE_SOURCE[0]}")"
SCRIPT_NAME="$(basename "$0")"

echo "$SCRIPT_NAME"
# List the various file format and thier extensions 
LIST_DOCS=("doc" "docx" "pdf" "txt")
LIST_IMAGES=("jpg" "jpeg" "png" "gif")
LIST_AUDIOS=("mp3" "wav" "ogg" "aac" "m4a" "mp4" "wma" "aiff" "au" "vox")
LIST_VIDEOS=("mp4" "avi" "mov" "wmv" "mpeg" "mpg" "m4v" "mkv" "flv" "webm")

# Check if the images, videos, audios and documents directory exist
for dir_name in images videos documents audios others; do 
    if [ ! -d "$CURR_DIR/$dir_name" ]; then
        mkdir "$CURR_DIR/$dir_name"
    fi
done

# Read all the files and sort them
for file in "$CURR_DIR"/*
do 
    # Check if the current file is not the script itself
    if [ "$file" = "$CURR_DIR/$SCRIPT_NAME" ]; then 
        continue
    fi

    if [ -d "$file" ]; then
        continue
    fi

    # Move the file to the destination directory
    case "${file##*.}" in 
        "${LIST_DOCS[@]}")
            echo "Moving $file to documents/"
            mv $file "$CURR_DIR/documents/"
            ;;
        "${LIST_IMAGES[@]}")
            echo "Moving $file to images/"
            mv $file "$CURR_DIR/images/"
            ;;
        "${LIST_VIDEOS[@]}")
            echo "Moving $file to videos/"
            mv $file "$CURR_DIR/videos/"
            ;;
        "${LIST_AUDIOS[@]}")
            echo "Moving $file to audios/"
            mv $file "$CURR_DIR/audios/"
            ;;
        *)
            echo "Moving $file to others/"
            mv "$file" "$CURR_DIR/others"
            ;;
    esac

done

echo -e "Your files are now sorted :) \nProcess terminated"